# Generated by Django 2.2.7 on 2019-11-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_keywords', models.TextField()),
                ('diagnosis', models.CharField(max_length=300)),
            ],
        ),
    ]
